#version: "3"
#services:
#  db:
##    image: mysql
#    build:
#      context: db
#    environment:
#      - MYSQL_ROOT_PASSWORD=my-secret-pw
##      - MYSQL_DATABASE=centrum
#    networks:
#    - spring-mysql
##    command: init.sql
##    env_file:
##      - default.env
#    ports:
#      - "3306:3306"
#    expose:
#      - 3306
##    command: mysql init.sql
#  backend:
#    networks:
#      - spring-mysql
#    ports:
#      - "8080:8080"
#    expose:
#      - 8080
#    build:
#      context: backend
#    depends_on:
#      - db
#networks:
#  spring-mysql:


version: "3"
services:
  server:
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/centrum?useSSL=false
    networks:
      - springmysql-net
    build:
      context: backend


  mysqldb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=centrum
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
  frontend:
    build:
      context: ../frontend/react
    depends_on:
      - server
    ports:
      - "3000:3000"
    links:
      - server

networks:
  springmysql-net: